[package]
name = "rs_de_zero"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
ndarray-linalg = "0.16.0"
num = "0.4.0"
assert_approx_eq = "1.1.0"
